### ISSUE TITLE
Make sure iOS and Android models matches

### ISSUE THREAD

**Issue by nhachicha** [realm/my-first-realm-app#12]
Having the same Realm schema on iOS & Android will allow cross binding tests. 

- [ ] Make sure the model matches in all tutorials 
- [ ] Test that each tutorial work across binding

**Comment by dhmspector** [comment]
In the `Project` model we should change the `id` property to `projectId` to  match the structure we have in the `Item` model where it's ID property is `itemId`   FWIW, `id` is a reserved word in ObjectiveC (it represents the "any" object type in ObjC) and may cause issues with the ObjC runtime if we used it).
