### ISSUE TITLE
Does not work with non-cloud ROS

### ISSUE THREAD

**Issue by mgeerling** [realm/my-first-realm-app#13]
I had to change my constants file to look like the following for it to work with on-prem ROS: 

```import Foundation
struct Constants {
    // ****
    // **** Replace the "MY_INSTANCE_ADDRESS" here with the hostname of your
    // **** Realm Cloud instance or the URL of your on-premises Realm Object Server
    // ****
    
    static let AUTH_URL = URL(string: "http://127.0.0.1:9080")!
    
    static var REALM_URL: URL {
        let realmsUrlString = Constants.AUTH_URL.absoluteString.replacingOccurrences(of: "http://", with: "realm://")
        return URL(string: "\(realmsUrlString)/ToDo")!
    }
    
}```

**Comment by dhmspector** [comment]
@mgeerling 

Is this is the `nickname` auth issue? Or simply need to change the documentation like so:

struct Constants {
    // **** Realm Cloud Users:
    // **** Replace the "MY_INSTANCE_ADDRESS" here with the hostname of your
    // **** Realm Cloud instance or the URL of your on-premises Realm Object Server
    // ****
    // **** ROS On-Premises Users
    // **** Replace `https://MY_INSTANCE_ADDRESS ` with the address of your
   // **** your ROS server, e.g.: "http://127.0.0.1:9080"

    static let AUTH_URL = URL(string: "https://MY_INSTANCE_ADDRESS")!
    
    static var REALM_URL: URL {
        let realmsUrlString = Constants.AUTH_URL.absoluteString.replacingOccurrences(of: "http://", with: "realm://")
        return URL(string: "\(realmsUrlString)/ToDo")!
    }
    
}```

**Comment by mgeerling** [comment]
It wasn't actually a nickname auth issue (originally, that was the thought).  
`let realmsUrlString = Constants.AUTH_URL.absoluteString.replacingOccurrences(of: "http://", with: "realm://")`
Doesn't this line still need to be `https` for cloud?

**Comment by bigfish24** [comment]
Yes cloud is https/realms if you run locally with ROS likely you don’t have SSL so when I verified nickname auth in run by default with local ROS I edited it to this.

**Comment by dhmspector** [comment]
I will probably change this up to be just direct declarations  - Max wrote this, and although it's a clever use of sting substitution it fails in the on-prem ROS case.

**Comment by dhmspector** [comment]
Fixed: updated the docs to show both cloud and on-prem styles of endpoints.
