### ISSUE TITLE
Object Level Permission 

### ISSUE THREAD

**Issue by nhachicha** [realm/my-first-realm-app#15]
_This issue discusses the design of the ObjectLevelPermission tutorial, once it's available for the bindings._

we could use this type of permission configuration https://github.com/realm/realm-sync/pull/1868/files#diff-0e3567aa4be9697779a43bc487abdcf9R441 which should allow creating a normal class where users can modify their objects, but not necessarily see objects of other users. 

It the context of the `ToDo` app this could be translated into restricting access into the `Project` class, so only the owner can see it & modify it. I think it's a nice transition from the `PartialSync` demo where everyone can still query for others `Project` and edit them 

WDYT @dhmspector @bigfish24 ?

**Comment by bigfish24** [comment]
@nhachicha yeah I like it, I was thinking this would work on the `Project`. This keeps it simpler than a more advanced system where only certain users can see certain `Project` objects which would mean you have to introduce sharing concept.
