### ISSUE TITLE
ToDo Xcode app metadata

### ISSUE THREAD

**Issue by ironage** [realm/my-first-realm-app#24]
The iOS tutorial calls for adding some new files to a clone of this project (eg. [here](https://docs.realm.io/platform/v/3.x/getting-started/ios-quick-start/step-2-adding-partial-sync#step-4:-adding-the-project-model)) and doing this generates a template copyright header at the top of the new file. But the auto copyright is going to "Maximilian Alexander" which I believe is incorrect for new files, and may confuse people. I suggest removing this name from the Xcode project metadata entirely or changing it to "Realm"

![Screen Shot 2018-03-13 at 16.11.43.png](https://images.zenhubusercontent.com/599756008f62dc7798c350fc/8238d71d-6457-4d07-86b0-9d8ca90a6918)

**Comment by bdash** [comment]
It might just be a matter of removing `ORGANIZATIONNAME` from here: https://github.com/realm/my-first-realm-app/blob/92540f900a78d3795c533d6deb50c3f166621be6/ios/SyncIntro/ToDo.xcodeproj/project.pbxproj#L131

(and the other project files)
