### ISSUE TITLE
Unable to login using SyncCredentials.usernamePassword

### ISSUE THREAD

**Issue by DanielAsher** [realm/my-first-realm-app#34]
#### Expected Results

Ability to login using `SyncCredentials.usernamePassword`

#### Actual Results

`Thread 1: Fatal error: The provided credentials are invalid or the user does not exist.`

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

I replace the call to                
` let creds = SyncCredentials.nickname(username, isAdmin: true)`
with
`let creds = SyncCredentials.usernamePassword(username: username, password: username, register: true)`

#### Version of Realm and tooling
Realm version(s): ? 3.5.0
Realm Cloud

Android Studio / XCode version: ? Xcode 9.3

Which device OS version and device: ? iOS 11 Simulator

**Comment by mgeerling** [comment]
@DanielAsher , are you still facing this?  I have this working fine on my project

**Comment by DanielAsher** [comment]
@mgeerling I've changed back `usernamePassword ` and this seems to be working now (Realm 3.7.5). I will reopen if I run into further problems.
